name: steps_counter
description: Steps counter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  injectable: ^2.1.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  flutter_local_notifications: ^13.0.0
  notification_permissions: ^0.6.1
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
